### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by robinandeer** [robinandeer/vegan#2]
I don't think there's any reason to fork and work on different repos for this. I added you as a collaborator so you should have push access to this repo directly.

If we want to be real fancy (and we might need to in order for the domains to work) we can setup a separate GitHub organization. I found that these are available:
- github.com/vegans
- github.com/veganism

/ping @guillermo-carrasco

**Comment by guillermo-carrasco** [comment]
Tack tack! 

The reason of forking was more about you reviewing my pull requests, but we can do that anyways just working on branches. Maybe we can talk about the domains later? When we have more content. But still, why would we need one?

:-)

**Comment by robinandeer** [comment]
You are cute, hehe. Most folks would buy the domain long before starting the project. But there's no rush :smile: - just with a proper domain it spells confidence.

Otherwise I like the plan.
